all:
	g++ main.cpp -o main

test1:
	./main [your-parameters-for-test1]

test2:
	./main [your-parameters-for-test2]

test3:
	./main [your-parameters-for-test3]

test4:
	./main [your-parameters-for-test4]
