all:
	javac Main.java

test1:
	java Main [your-parameters-for-test1]

test2:
	java Main [your-parameters-for-test2]

test3:
	java Main [your-parameters-for-test3]

test4:
	java Main [your-parameters-for-test4]
